### ISSUE TITLE
Question for the course personnel

### ISSUE THREAD

**Issue by venlavie** [enehlauri/ofbiz-framework#3]
Does the bug fix need to have the Sonarcloud-analysis also, or only in the new feature implementation part of the project?

**Comment by venlavie** [comment]
Hello,

Every time you produce code, you run Sonar analyser. So, in both phases (bug fix and new feature) Sonar is used. It would be good software engineering practice to run Sonar analyser before pull request to the original OS project repo. If you get Sonar issues, fix/refactor what you see necessary, and run analyser again.

At Moodle there is pdf file "Guidelines to fill-in the quality diary report".

It says: "Every time you analyze your code with Sonarcloud and refactor the SonarQube rules violated in your code, you must report it in the diary. "

**Comment by laurakurkinen** [comment]
Priority: Low
