### ISSUE TITLE
Connect SonarCloud to your CI/CD pipeline

### ISSUE THREAD

**Issue by laurakurkinen** [enehlauri/ofbiz-framework#5]
– After implementing the new feature
• Connect SonarCloud to your CI/CD pipeline.
• Fill-inn the quality diary (diary.xlsx) listing the sonar issues affecting ONLY the code you implemented
– Remember that there is no correlation and we are not going to compare the file quality-issues.xlsx with the quality diary for evaluating the project
outcome.
• Refactor the code removing all the sonar issues in the code you need to change
• Commit the changes with commit message “Sonar Refactoring …”
• Complete the quality diary listing the refactorings applied.

**Comment by laurakurkinen** [comment]
Priority: High

**Comment by enehlauri** [comment]
Hours used: 8
