### ISSUE TITLE
Submit the project in Moodle

### ISSUE THREAD

**Issue by laurakurkinen** [enehlauri/ofbiz-framework#6]
Submission should contain:
- A text file containing link to the original Open Source project issue, link to your pull
request, link to your own project repository, SonarCloud and Kanban board (if used other
than ZenHub)
- Gxx-diary.xls
- Gxx-Quality-issue.xls
where Gxx is your group number, e.g. G42.

**Comment by laurakurkinen** [comment]
Priority: High

**Comment by enehlauri** [comment]
Hours spent: 1
